Berechnung der Mietstufe aus Datenmodell entfernt
Hartz-Arbeit/LohntDat pull request #12
Opened 2022-08-09 16:45 UTC by jpv-os

Für die Eingabe der Unterkunft wird lediglich die Mietstufe und das Wohnverhältnis benötigt. Die Mietstufe kann mithilfe des Bundeslandes und des Wohnorts aus einer Tabelle abgelesen werden (für die Tabelle, siehe Pull Request: https://github.com/Hartz-Arbeit/LohntDat/pull/9). Das Frontend muss also die Informationen aus der Tabelle verwenden, um die Mietstufe auszulesen. Für das Eingabeformular, welches in dieser Datei modelliert wird, ist damit der Wohnort unerheblich und das Eingabemodell kann im `Unterkunft` Interface weiter vereinfacht werden.

2022-08-09 16:59 UTC, jpv-os commented
Ups, Branch umbenannt und Pull Request wurde geschlossen. Ich eröffne neu.

2022-08-10 23:00 UTC, cr4yfish requested changes

2022-08-10 23:00 UTC, cr4yfish commented on datenmodell
> +  wohnverhaeltnis: Wohnverhaeltnis;
_wohnverhaeltnis_ ist vom Typ _Wohnverhaeltnis_, aber das Enum _Wohnverhaeltnis_ aus Zeile 113 wurde entfernt. 
Übersehe ich was, oder ist der Typ jetzt undefined?

2022-08-10 23:04 UTC, ByteDream requested changes
Datei zu `alg2-formular.ts` zurück benennen

2022-08-10 23:04 UTC, ByteDream commented on datenmodell
> -}
Die `Wohnverhaeltnis` enum wurde entfernt, damit alles funktioniert muss sie wieder hinzugefügt werden

2022-08-10 23:05 UTC, ByteDream commented on datenmodell
> +  wohnverhaeltnis: Wohnverhaeltnis;
Typescript streikt wenn die enum nicht vorhanden ist

2022-08-11 14:33 UTC, jpv-os commented on datenmodell
> -}
Wieder hinzugefügt, wurde fälschlicherweise entfernt

2022-08-11 14:34 UTC, jpv-os commented
Wie im anderen PR auch, gab's hier auf meiner Seite etwas Verwirrung, weil ich die Online IDE von GitHub ausprobiert habe, und mir dabei Fehler passiert sind. Der Dateiname, sowie das fehlende Enum sind wieder korrigiert.

2022-08-11 14:37 UTC, ByteDream approved these changes

2022-08-11 18:14 UTC, cr4yfish approved these changes

2022-08-11 18:14 UTC, merged