Personen im Haushalt außerhalb BG sind optional
Hartz-Arbeit/LohntDat pull request #13
Opened 2022-08-09 16:48 UTC by jpv-os

Die Angabe zu der Anzahl der Personen im Haushalt ist optional und kann in der weiteren Berechnung falls nötig standardmäßig als 0 angenommen werden. Daher wird der Datentyp des Feldes `personenImHaushaltAusserhalbBG` geändert, sodass das Feld nun optional ausgefüllt werden kann, aber nicht mehr muss.

2022-08-09 16:59 UTC, jpv-os commented
Ups, Branch umbenannt und Pull Request wurde geschlossen. Ich eröffne neu.

2022-08-10 13:07 UTC, ByteDream commented
Wieso wurde die Datei zu `datenmodell-personen-im-haushalt` umbenannt?

2022-08-10 22:44 UTC, ByteDream requested changes
Datei zu alg2-formular.ts zurück benennen

2022-08-11 14:29 UTC, ByteDream approved these changes

2022-08-11 14:31 UTC, jpv-os commented
Ich habe für die beiden Commits in der Weboberfläche von Github gearbeitet, und dabei sind mir mit Branch- und Dateibenennung zwei Fehler passiert - ist jetzt korrigiert.

2022-08-11 18:31 UTC, cr4yfish approved these changes
Ein langer Weg um 1 Zeichen hinzuzufügen :D.

2022-08-11 18:32 UTC, merged