Allgemeine Beschreibung
Hartz-Arbeit/LohntDat pull request #15
Opened 2022-08-09 23:54 UTC by ByteDream

Ich hab mal eine Allgemeine Beschreibung über die Idee und das Ziel des Projekts gemacht. Sehr viel außer diese Informationen konnte man noch nicht hinschreiben, da sich vieles, was die genaue / technische Umsetzung betrifft, noch entschieden wird.
Bringt eventuell auch den ein oder anderen, der hier vorbeistolpert, sich näher damit zu beschäftigen.

2022-08-10 05:54 UTC, sebastianrauer commented
Topp! Würde das direkt nutzen für den weiteren Verlauf des Design Prototypen

2022-08-10 14:00 UTC, cr4yfish requested changes
Siehe mein comment.
Ansonsten find' ich das gut so.

2022-08-10 14:21 UTC, ByteDream commented on README.md
> +in dem ein Nutzer sich fragte, ob es wirtschaftlich im Hinblick auf den Winter 2022 und die damit verbundenen steigenden Energiepreise nicht mehr lohnt,
Stimmt, wurde behoben

2022-08-10 14:35 UTC, cr4yfish reviewed
Jo, sieht jetzt gut aus.

2022-08-10 14:36 UTC, cr4yfish commented
Ich hab mal noch nicht merging approved, da in #10 über 2 Reviews vor merging nachgedacht wurde.

2022-08-10 14:52 UTC, ByteDream commented
Jo, halte ich auch für sinnvoll

2022-08-10 22:35 UTC, cr4yfish approved these changes

2022-08-10 23:40 UTC, ByteDream reviewed
Hab die Discussions hinzugefügt und den Text für Pull Request und Issues dementsprechend auch angepasst

2022-08-11 05:57 UTC, Eixix requested changes

2022-08-11 05:57 UTC, Eixix commented on README.md
> +in dem ein Nutzer sich fragte, ob es sich wirtschaftlich im Hinblick auf den Winter 2022 und die damit verbundenen steigenden Energiepreise nicht mehr lohnt,
`... nicht mehr lohnt ...` verstehe ich beim ersten Lesen als `Harz 4 lohnt sich nicht mehr`. Ein besserer erster Satz wäre meiner Meinung nach:

```markdown
Beginnend mit [diesem](https://www.reddit.com/r/Finanzen/comments/wihglw/app_hartziv_oder_arbeiten/) Post in [r/Finanzen](https://www.reddit.com/r/Finanzen/),
in dem sich ein Nutzer fragte, ob es sich wirtschaftlich im Hinblick auf den Winter 2022 und die damit verbundenen steigenden Energiepreise überhaupt noch lohnt zu arbeiten oder ob Hartz IV / ALG II rentabler wäre und man zur Berechnung dieser Frage eine App erstellen könnte wurde dieses Projekt ins Leben gerufen.

```

2022-08-11 09:37 UTC, cr4yfish commented on README.md
> +in dem ein Nutzer sich fragte, ob es sich wirtschaftlich im Hinblick auf den Winter 2022 und die damit verbundenen steigenden Energiepreise nicht mehr lohnt,
Der Satz ist etwas lang.

Ohnehin fehlt da denke ich ein Komma:
```markdown
[...] eine App erstellen könnte **,** wurde dieses Projekt ins Leben gerufen.
```

Mein Vorschlag:
```markdown
Ein r/Finanzen Nutzer frage sich in [diesem] Post, ob es sich als Geringverdiener noch lohnt zu arbeiten, 
oder ob es rentabler wäre, ALG II (umg. Hartz IV) zu beziehen.

Um dies herauszufinden, schlug der Nutzer das Entwickeln einer App zur Berechnung dessen vor - und so wurde dieses Projekt ins Leben gerufen.
```

2022-08-11 09:52 UTC, ByteDream commented on README.md
> +in dem ein Nutzer sich fragte, ob es sich wirtschaftlich im Hinblick auf den Winter 2022 und die damit verbundenen steigenden Energiepreise nicht mehr lohnt,
Ja, die Länge hat mich auch ein bisschen gestört, deinen einen Vorschlag finde ich besser, 

Am Ende würde ich statt 
```
[...] - und so wurde dieses Projekt ins Leben gerufen.
```
Das hier verwenden:
```
[...] - wodurch dieses Projekt ins Leben gerufen wurde.
```

2022-08-11 14:10 UTC, ByteDream reviewed
Hab noch einen Hinweis auf den Projekte Tab hinzugefügt

2022-08-11 15:10 UTC, Eixix requested changes

2022-08-11 15:10 UTC, Eixix commented on README.md
> +Ein [r/Finanzen](https://www.reddit.com/r/Finanzen/) Nutzer frage sich in [diesem](https://www.reddit.com/r/Finanzen/comments/wihglw/app_hartziv_oder_arbeiten/) Post, ob es sich als Geringverdiener n
`... fragTe sich ...`

Und ich denke die Energiekosten sollten doch als Aufhänger mit rein.
```
... ob es sich als Geringverdiener (gerade bei den gestiegenen Energiekosten) noch lohnt zu arbeiten oder ob es rentabler wäre, ALG II (umg. Hartz IV) zu beziehen.
```

2022-08-11 15:14 UTC, ByteDream commented on README.md
> +Ein [r/Finanzen](https://www.reddit.com/r/Finanzen/) Nutzer frage sich in [diesem](https://www.reddit.com/r/Finanzen/comments/wihglw/app_hartziv_oder_arbeiten/) Post, ob es sich als Geringverdiener n
Done

2022-08-11 15:19 UTC, Eixix approved these changes
Perfekt, sorry für das 2-malige ablehnen 😄

2022-08-11 15:20 UTC, merged

2022-08-11 15:21 UTC, ByteDream commented
> Perfekt, sorry für das 2-malige ablehnen smile

Kein Ding, waren ja immer sinnvolle Gründe dahinter